### ISSUE TITLE
Auto image

### ISSUE THREAD

**Issue by Planks** [zephyyrr/esacontroller#10]
When you select an in1606 source manually, it should send an 'auto image' command to the in1606 once the source has been selected 

There should be an 'auto image' button in the in1606 area (could be called Reset Crop)

When you save a preset with in1606 settings you should be able to toggle whether to use the current cropping values, or just use auto image.

PC / HDMI console will be cropped perfectly by auto image
Analog will generally be using one of Edenal's manual cropping presets he noted down at DH

**Comment by zephyyrr** [comment]
Related to zephyyrr/ESARack#7
