### ISSUE TITLE
Name inputs for IN1606

### ISSUE THREAD

**Issue by zephyyrr** [zephyyrr/esacontroller#9]
The IN1606 should have descriptive names. Need list from Planks, Maxie or Edenal.

**Comment by Planks** [comment]
Crosspoint Preset names

Preset 1: RGB
Preset 2: Component 
Preset 3: HDMI Console
Preset 4: PC

in1606 input names
Input 1: RGB/Component pass-through
Input 2: HDMI Console
Input 3: RGB/Component via OSSC
Input 4: PC

**Comment by Planks** [comment]
Edenal has a list of pre-set presets to pre-program at the bottom of this page
https://docs.google.com/document/d/1Oh-AgCCfanJIGTUgY172VmPsR76aIiKSxecq-xkXUNM/edit#
